### PR TITLE
Add config.json for server and algo assigining

### PR DESCRIPTION
**Pull request by flow6979**

### CODE REVIEW

**Review by VandanaKumari18 — COMMENTED** [review]
Should we change the server to a different port? WDYT?

**Comment by flow6979** [comment]
right, we can do that, i'll update once finish with it.

**Comment by flow6979** [comment]
**_`INSIDE IPv4: (0.0.0.0 to 255.255.255.255)`_**

`private IP range (not routable on the internet)`

- (172.16.0.0 to 172.31.255.255)
- (10.0.0.0 to 10.255.255.255)
- (192.168.0.0 to 192.168.255.255)

      
` Link-Local Addresses (used for local network communications)`
- (169.254.0.0 to 169.254.255.255)


`Loopback Addresses (used for internal testing)`
- (127.0.0.0 to 127.255.255.255)

`Reserved for Multicast, Documentation, and Experimental Uses`
- **Multicast**: (224.0.0.0 to 239.255.255.255)
- **Documentation**: (192.0.2.0 to 192.0.2.255)
- **Experimental**: (240.0.0.0 to 255.255.255.255)

**Comment by flow6979** [comment]
so we'll be choosing any ip in this range - (172.16.0.0 to 172.31.255.255)

lets use 172.16.0.1

ports are fing ig

**Comment by VandanaKumari18** [comment]
> so we'll be choosing any ip in this range - (172.16.0.0 to 172.31.255.255)
> 
> lets use 172.16.0.1
> 
> ports are fing ig

Thankyou for the changes @flow6979 . I am assuming we can also test using different port number other than 8080-8084. 

we can use ports 8085, 8086, 8087, 8088, or any other port in the 8000-8999 range (or beyond). These ports are available for general use, and as long as they aren't already in use by another application or service on our machines. This may help us figure out any compatibility issues with these ports. 

Currently, We will apply
8090 - local host.
8091-8093 - Load balancer host.

**Review by VandanaKumari18 — APPROVED** [review]

**Pull request merged**
